### ISSUE TITLE
Failed Conversion to COG, Missing codec

### ISSUE THREAD

**Issue by BradleyBurrellSD** [Esri/OptimizeRasters#95] opened 2019-10-28 16:00 UTC
I am trying it implement OptimizeRasters to convert GeoTIFs to COGs as part of a larger workflow, but I am unable to open the resulting COGs due to a Missing Codec, via the following code:
```
import subprocess
import validate_cloud_optimized_geotiff


def optimize_raster_tif2cog(python_exe, optimize_raster_python, path_to_input_folder, path_to_output_folder):
    mode = "tif_cog"
    command_line_command = """{} {} -input={} -output={} -mode={}""".format(python_exe, optimize_raster_python,
                                                                            path_to_input_folder, path_to_output_folder,
                                                                            mode)
    subprocess.call(command_line_command)


if __name__ == "__main__":
    optimize_raster_tif2cog(python_exe='C:\\Users\\bradl\\Anaconda3\\envs\\TestEnv_3.6\\python.exe',
                            optimize_raster_python='C:\\Image_Mgmt_Workflows\\OptimizeRasters\\OptimizeRasters.py',
                            path_to_input_folder='D:\\OptimizeRaster_Input',
                            path_to_output_folder='D:\\OptimizeRaster_Output')

    validate_cloud_optimized_geotiff.validate("D:\\OptimizeRaster_Output\\SU.tif")
```

to which I am getting this output,

> C:\Users\bradl\Anaconda3\envs\TestEnv_3.6\python.exe D:/Dropbox/Tech_Docs/OptimizeRasters_ViaPython/GeoTIF_2_COG.py
> OptimizeRasters.py v2.0.5j/20190908
> Convert raster formats to a valid output format through GDAL_Translate.
> 
> Please Note:
> OptimizeRasters.py is entirely case-sensitive, extensions/paths in the config file are case-sensitive and the program will fail if the correct path/case is not entered at the cmd-line or in the config file.
> 
> Invalid log-path (c:\image_mgmt_workflows\optimizeraster\logs). Resetting to (C:\Image_Mgmt_Workflows\OptimizeRasters\logs)
> Log-path set to (C:\Image_Mgmt_Workflows\OptimizeRasters\logs)
> log-msg:version=v2.0.5j/20190908
> log-msg:-config="C:/Image_Mgmt_Workflows/OptimizeRasters/OptimizeRasters.xml" -input="D:/OptimizeRaster_Input" -mode="tif_cog" -output="D:/OptimizeRaster_Output"
> log-msg:Mode=tif
> log-msg:RasterFormatFilter=['tif', 'TIF', 'mrf']
> log-msg:ExcludeFilter=['tmp', 'ovr', 'rrd', 'idx', 'lrc', 'mrf_cache', 'pjp', 'ppng', 'pft', 'pzp']
> log-msg:Compression=lerc
> log-msg:Quality=85
> log-msg:BuildPyramids=true
> log-msg:PyramidFactor=2 4 8 16 32 64
> log-msg:PyramidCompression=JPEG
> log-msg:BlockSize=512
> log-msg:KeepExtension=True
> log-msg:Threads=2
> log-msg:LogPath=c:\Image_Mgmt_Workflows\OptimizeRaster\Logs
> log-msg:IncludeSubdirectories=True
> log-msg:Out_S3_ID=Out_S3_ID
> log-msg:Out_S3_Secret=Out_S3_secret_key
> log-msg:Out_S3_Bucket=Out_BucketName
> log-msg:Out_S3_ParentFolder=Out_S3Parent_folder
> log-msg:Out_S3_Upload=F
> log-msg:Out_S3_DeleteAfterUpload=True
> log-msg:In_S3_ID=In_S3_ID
> log-msg:In_S3_Secret=In_S3_Secret
> log-msg:In_S3_Bucket=In_BucketName
> log-msg:In_S3_ParentFolder=sampletest/02042014
> log-msg:cog=True
> log-msg:Checking for updates..
> log-msg:Copying non rasters/aux files (D:/OptimizeRaster_Input/=>D:/OptimizeRaster_Output/)..
> log-msg:Done.
> log-msg:Converting..
> log-msg:[Resume] Creating job (C:\Image_Mgmt_Workflows\OptimizeRasters\OR_20191028T153520680142.orjob)
> log-msg:Copying non rasters/aux files (D:/OptimizeRaster_Input/=>D:/OptimizeRaster_Output/)..
> log-msg:Done.
> log-msg:Converting..
> log-msg:Applying compression (D:/OptimizeRaster_Input/SU.tif)
> log-msg:messages:
> log-msg:b'Input file size is 4000, 4000'
> log-msg:b'0...10...20...30...40...50...60...70...80...90...100 - done.'
> log-msg:Status: (OK).
> log-msg:Creating pyramid ("D:/OptimizeRaster_Output/SU.tif.cogtiff")
> log-msg:messages:
> log-msg:b'0...10...20...30...40...50...60...70...80...90...100 - done.'
> log-msg:Status: (OK).
> log-msg:Creating cloud optimized GeoTIFF (D:/OptimizeRaster_Output/SU.tif)
> log-msg:messages:
> log-msg:b'Input file size is 4000, 4000'
> log-msg:b'0...10...20...30...40...50...60...70...80...90...100 - done.'
> log-msg:Status: (OK).
> log-msg:[MV] C:\Image_Mgmt_Workflows\OptimizeRasters\logs\OR_20191028T153520680142.orjob
> log-msg:Done..
> 
> log-status:[OK]
> Time taken> 19.188308s
> 
> Done..
> Traceback (most recent call last):
>   File "D:/Dropbox/Tech_Docs/OptimizeRasters_ViaPython/GeoTIF_2_COG.py", line 19, in <module>
>     validate_cloud_optimized_geotiff.validate("D:\\OptimizeRaster_Output\\SU.tif")
>   File "D:\Dropbox\Tech_Docs\OptimizeRasters_ViaPython\validate_cloud_optimized_geotiff.py", line 74, in validate
>     'Invalid file : %s' % gdal.GetLastErrorMsg())
> validate_cloud_optimized_geotiff.ValidateCloudOptimizedGeoTIFFException: Invalid file : Cannot  open TIFF file due to missing codec.
> 
> Process finished with exit code 1

I am using a tile for the Ordnance Survey's [1:250 000 Scale Colour Raster](https://www.ordnancesurvey.co.uk/business-government/products/250k-raster), as test data.

The COG validation was carried out using COG Contributors Design [validate_cloud_optimized_geotiff script](https://raw.githubusercontent.com/vincentsarago/gdal/master/gdal/swig/python/samples/validate_cloud_optimized_geotiff.py)

Any help would be greatly appreciated.

**Comment by Chamlika** [comment] 2019-10-29 10:30
@BradleyBurrellSD This could be something internal to 'validate_cloud_optimized_geotiff' code but I'm not sure at this point if it's related to the output COG raster generated by the OR. To test, could you update the CMD in code as shown below and give it a try. I'd like to add a COG template supplied by OR setup to the CMD to see if that works.

config = r'c:\Image_Mgmt_Workflows\OptimizeRasters\Templates\Templates\Imagery_to_COG_JPEG.xml'
command_line_command = """{} {} -input={} -output={} -config={}""".format(python_exe, optimize_raster_python, path_to_input_folder, path_to_output_folder, config                                                                       )

Also if you can, let's have your input raster on net so I could test with it. 

Thanks!

**Comment by BradleyBurrellSD** [comment] 2019-10-29 10:55
@Chamlika, I have mended the code as such
```
import subprocess
import validate_cloud_optimized_geotiff

def optimize_raster_tif2cog(python_exe, optimize_raster_python, path_to_input_folder, path_to_output_folder):
    config = r'c:\Image_Mgmt_Workflows\OptimizeRasters\Templates\Imagery_to_COG_JPEG.xml'
    command_line_command = """{} {} -input={} -output={} -config={}""".format(python_exe, optimize_raster_python,
                                                                              path_to_input_folder,
                                                                              path_to_output_folder, config)
    subprocess.call(command_line_command)

if __name__ == "__main__":
    optimize_raster_tif2cog(python_exe='C:\\Users\\bradl\\Anaconda3\\envs\\TestEnv_3.6\\python.exe',
                            optimize_raster_python='C:\\Image_Mgmt_Workflows\\OptimizeRasters\\OptimizeRasters.py',
                            path_to_input_folder='D:\\OptimizeRaster_Input',
                            path_to_output_folder='D:\\OptimizeRaster_Output')

    validate_cloud_optimized_geotiff.validate("D:\\OptimizeRaster_Output\\SU.tif")
```
The only change to your comment was to change the pathway to match my system.

I'm afraid that didn't work resulting in this output:

> C:\Users\bradl\Anaconda3\envs\TestEnv_3.6\python.exe D:/Dropbox/Tech_Docs/OptimizeRasters_ViaPython/esri_cog_converter-GitHub.py
> OptimizeRasters.py v2.0.5j/20190908
> Convert raster formats to a valid output format through GDAL_Translate.
> 
> Please Note:
> OptimizeRasters.py is entirely case-sensitive, extensions/paths in the config file are case-sensitive and the program will fail if the correct path/case is not entered at the cmd-line or in the config file.
> 
> Log-path set to (C:\Image_Mgmt_Workflows\OptimizeRasters\logs)
> log-msg:version=v2.0.5j/20190908
> log-msg:-config="c:/Image_Mgmt_Workflows/OptimizeRasters/Templates/Imagery_to_COG_JPEG.xml" -input="D:/OptimizeRaster_Input" -output="D:/OptimizeRaster_Output"
> log-msg:Mode=tif
> log-msg:RasterFormatFilter=['tif', 'tiff', 'TIF', 'TIFF', 'img', 'jp2', 'JP2', 'IMG', 'JPG', 'jpg', 'sid', 'SID']
> log-msg:ExcludeFilter=['tmp', 'rrd', 'idx', 'lrc', 'mrf_cache', 'pjp', 'ppng', 'pft', 'pzp', 'ovr', 'aux.xml', 'aux', 'tfw', 'TFW', 'pjg']
> log-msg:IncludeSubdirectories=true
> log-msg:Compression=JPEG
> log-msg:Quality=85
> log-msg:BuildPyramids=true
> log-msg:Predictor=2
> log-msg:PyramidSampling=average
> log-msg:PyramidCompression=JPEG
> log-msg:BlockSize=512
> log-msg:KeepExtension=false
> log-msg:Threads=4
> log-msg:CloudUpload=false
> log-msg:Out_S3_DeleteAfterUpload=true
> log-msg:cog=True
> log-msg:Checking for updates..
> log-msg:Copying non rasters/aux files (D:/OptimizeRaster_Input/=>D:/OptimizeRaster_Output/)..
> log-msg:Done.
> log-msg:Converting..
> log-msg:[Resume] Creating job (C:\Image_Mgmt_Workflows\OptimizeRasters\OR_20191029T104854943036.orjob)
> log-msg:Copying non rasters/aux files (D:/OptimizeRaster_Input/=>D:/OptimizeRaster_Output/)..
> log-msg:Done.
> log-msg:Converting..
> log-msg:Applying compression (D:/OptimizeRaster_Input/SU.tif)
> log-msg:messages:
> log-msg:b'Input file size is 4000, 4000'
> log-msg:b'0...10...20...30...40...50...60...70...80...90...100 - done.'
> log-msg:Status: (OK).
> log-msg:Creating pyramid ("D:/OptimizeRaster_Output/SU.tif.cogtiff")
> log-msg:Using GDALInfo ("D:/OptimizeRaster_Output/SU.tif.cogtiff")..
> log-msg:<PyramidFactor> set to (2 4 8)
> log-msg:messages:
> log-msg:b'0...10...20...30...40...50...60...70...80...90...100 - done.'
> log-msg:Status: (OK).
> log-msg:Using GDALInfo ("D:/OptimizeRaster_Input/SU.tif")..
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\Users\bradl\Anaconda3\envs\TestEnv_3.6\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Users\bradl\Anaconda3\envs\TestEnv_3.6\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py", line 4170, in compress
>     ret = gdalInfo.bandInfo
>   File "C:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py", line 1249, in bandInfo
>     if (v.startswith('Band ')):
> TypeError: startswith first arg must be bytes or a tuple of bytes, not str
> 
> log-msg:[MV] C:\Image_Mgmt_Workflows\OptimizeRasters\logs\OR_20191029T104854943036.orjob
> log-msg:Done..
> 
> log-status:[OK]
> Time taken> 14.67532s
> 
> Done..
> Traceback (most recent call last):
>   File "D:/Dropbox/Tech_Docs/OptimizeRasters_ViaPython/esri_cog_converter-GitHub.py", line 26, in <module>
>     validate_cloud_optimized_geotiff.validate("D:\\OptimizeRaster_Output\\SU.tif")
>   File "D:\Dropbox\Tech_Docs\OptimizeRasters_ViaPython\validate_cloud_optimized_geotiff.py", line 74, in validate
>     'Invalid file : %s' % gdal.GetLastErrorMsg())
> validate_cloud_optimized_geotiff.ValidateCloudOptimizedGeoTIFFException: Invalid file : D:\OptimizeRaster_Output\SU.tif: No such file or directory
> 
> Process finished with exit code 1

The file used is uploaded here: [OptimizeRaster_Input.zip](https://github.com/Esri/OptimizeRasters/files/3783153/OptimizeRaster_Input.zip)

**Comment by Chamlika** [comment] 2019-11-03 10:46
@BradleyBurrellSD Let's change to the following template and give it a try. Also please update with the latest GitHub source, few error check enhancements added to source. 

config = r'c:\Image_Mgmt_Workflows\OptimizeRasters\Templates\Imagery_to_COG_DEF.xml'
I've tested with your input raster and it looks OK.

**Comment by abhiataero** [comment] 2020-01-23 09:17
@BradleyBurrellSD  I hope the issue is resolved, so i am closing it. if you are still seeing any error do let us know

**Closed by abhiataero** 2020-01-23 09:17 UTC
