### ISSUE TITLE
fail to retrieve right url to aws

### ISSUE THREAD

**Issue by gauteaasolaas** [Esri/OptimizeRasters#97] opened 2019-12-05 06:51 UTC
OptimizeRasters.py
line 2888:
loc = bucketCon.get_bucket_location(Bucket=self.m_bucketname)['LocationConstraint']
returns 'EU' and url https://s3.EU.amazonaws.com
should have returned 'eu-west-1' to generate url: https://s3.eu-west-1.amazonaws.com

**Comment by Chamlika** [comment] 2019-12-05 14:19
@gauteaasolaas @abhiataero I suspect the boto3 version here, I'm unable to reproduce. Could you please upgrade the boto3 using the following command and have a look. 

pip install --upgrade boto3

Thanks!

**Comment by gauteaasolaas** [comment] 2019-12-06 09:32
I tried without success on 10.6.1. Then installed 10.7.1 and tried again to no awail.
Inspecting the available variables in the session-object I noticed that the line
region = session.region_name
would solve the problem.
Not sure how that will work in Python3.

**Comment by Chamlika** [comment] 2019-12-08 11:30
@gauteaasolaas Can you provide me temporary credentials to access a similar bucket to test? 

Thanks!

**Comment by Chamlika** [comment] 2021-07-16 06:17
@gauteaasolaas virtual hosted addressing (bucket name is now part of the domain) requirement for AWS URLs has been implemented for OR. The path style addressing, as recommended and made obsolete by AWS is no longer supported within OR.
Your issue I believe is no longer relevant due to this change. I'll be closing the issue, but please reopen if it's necessary, thanks!

**Closed** 2021-07-16 06:17 UTC
Labels: unable to reproduce.
