### ISSUE TITLE
Tool does not upload data to Azure blob storage when run out of ArcGIS Pro

### ISSUE THREAD

**Issue by alexkemp94** [Esri/OptimizeRasters#80] opened 2019-02-07 13:17 UTC
When trying to convert .tif imagery to MRF and upload to Azure blob storage using the OptimizeRasters tool in ArcGIS Pro, the converted MRF files were being created and stored in the local temp folder but they were not being uploaded to the storage container. The tools appears to rrecognise the the container but cannot access it. This appears to be the case for all machine that are running the tool using ArcGIS Pro 2.2.0. The same process (same storage container and Azure account etc.) can be carried out in ArcMap and so it appears the problem does indeed relate to using it within ArcGIS Pro.

**Comment by Chamlika** [comment] 2019-02-13 09:49
@alexkemp94 Could you check with the latest code changes on GitHub to see if everything looks OK with OptimizeRasters using Azure within the ArcGIS Pro? Thanks!

**Comment by alexkemp94** [comment] 2019-02-13 14:50
Hi @Chamlika, thanks for getting back to me on this. I've just tested the updates and it appears that the MRF files do indeed appear in an Azure Storage Container when using the OptimizeRasters tool in Pro now - thanks! However, I'm having trouble reading the .mrf raster proxy files back in Pro after they have been created. The images appear with the correct dimensions but there are no data values in the raster grid. I have set my environment variables to read out of the storage account but still no success. Do you have any advice on this? Thanks, Alex

**Comment by abhiataero** [comment] 2019-02-18 11:56
closing the issue as per discussion with @alexkemp94 the issue is fixed

**Closed by abhiataero** 2019-02-18 11:56 UTC
